### PR TITLE
Add visibility to productinterface

### PR DESCRIPTION
**Pull request by Jade-GG**
I forgot that this is not standard magento, so this is actually necessary for https://github.com/rapidez/core/pull/563

### CODE REVIEW

**Comment by royduin** [comment]
Don't forget the readme 😇

**Review by indykoning — APPROVED** [review]

**Comment by royduin** [comment]
Do we still need this?

**Comment by Jade-GG** [comment]
The parent PR is closed, but it could still be useful for compadre so that, if you do want this in your query, you have the ability to use it without having to make your own magento plugin? I don't really know exactly what the scope of compadre is supposed to be---whether it's only for standard rapidez things or also for stuff that may be useful but isn't standard rapidez.

**Comment by royduin** [comment]
Closing for now as it's not used

**Pull request closed without merging**
